default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: cloudbase_development
  host: localhost
  pool: 5
  username: deployment
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: cloudbase_test
  host: localhost
  pool: 5
  username: deployment
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: cloudbase
  host: localhost
  pool: 5
  username: deployment
  password: password
